add --dev flags for configure/make

diff --git a/jsconfigure b/jsconfigure
--- a/jsconfigure
+++ b/jsconfigure
@@ -1,2 +1,11 @@
 #! /bin/sh
-emconfigure ./configure  --disable-debug-info --disable-pcre 'CFLAGS=-O3'
+EXTRA_CONFIG_ARGS='CFLAGS=-O3'
+if [ "$1" == "--dev" ]; then
+  echo "Building development version"
+  EXTRA_CONFIG_ARGS=''
+fi
+
+echo "\n\n------------------------ 1/1 Invoking emconfigure... ------------------------------"
+trap 'exit' ERR  # bail on error
+set -x  # show the executed command
+emconfigure ./configure  --disable-debug-info --disable-pcre $EXTRA_CONFIG_ARGS
diff --git a/jsmake b/jsmake
--- a/jsmake
+++ b/jsmake
@@ -1,8 +1,23 @@
 #! /bin/sh
+CFLAGS='-03'
+if [ "$1" == "--dev" ]; then
+  echo "Building development version"
+  CFLAGS='-g4'
+fi
+
+echo "---------------------- Cleaning existing artifacts... ----------------------"
 make clean
+rm chktex.bc chktex.js* chktex.data a.out*
+
+trap 'exit' ERR  # From here on out bail on error
+
+echo "\n\n------------------------ 1/2 Invoking emake make... ------------------------"
 emmake make
-mv chktex chktex.bc
+
+echo "\n\n------------------------ 2/2 Invoking emcc... ------------------------------"
 # Disable seperate .mem file to keep everything self contained.
-emcc -O3 chktex.bc -o chktex.js --pre-js ./pre.js --memory-init-file 0 --embed-file chktexrc@/usr/local/etc/
-echo "Testing optimised binary"
+mv chktex chktex.bc
+emcc $CFLAGS chktex.bc -o chktex.js --pre-js ./pre.js --memory-init-file 0 --embed-file chktexrc@/usr/local/etc/
+
+echo "\n\n--------------------- Attempting to run binary ----------------------------"
 node chktex.js --version
